apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::471112615183:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-Lp9r3lXrANd3
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-pod-reader
      userarn: arn:aws:iam::471112615183:user/ramesh
      username: ramesh
kind: configmap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: 01b85e1d-22ba-48d6-9ed0-2940b637cf4c
#kubectl get configmap -n kube-system aws-auth -o yaml
